run-name: Uso de diferentes triggers
on:
  push:
    - master
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.py'
  issues:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: 'Lenguaje favorito'
        default: Python
        required: true
        type: choice
        options:
          - Python
          - JavaScript
          - Go
      nombre:
         description: 'Tu nombre'
         required: true
         default: Juan
         type: string
  schedule:
    - cron: '15 22 * * *'
jobs:
  hola-mundo-manual:
    runs-on: ubunto-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir nombre
        run: echo "USER_NAME=${{ inputs.nombre }}" >> $GITHUB_ENV
      - name: definir lenguaje
        run: echo "LANGUAGE=${{ inputs.lenguaje_favorito }}" >> $GITHUB_ENV
      - name: Correr script
        run: pyhon hola_lenguaje.py
  hola-mundo:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubunto-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable
        run: echo "USER_NAME=${{ github-actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python hola_mundo.py
